apiVersion: v2
name: onecx-help-ui
version: 0.0.0
description: OneCX Help UI
home: https://github.com/onecx/onecx-help-ui
keywords:
  - help
sources:
  - https://github.com/onecx/onecx-help-ui
maintainers:
  - name: OneCX Developer Team
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-angular-app
    version: 0.22.0
    repository: oci://ghcr.io/onecx/charts
    alias: app
